/* ============================================================
   BUILD — regenerate sw.js from what is actually on disk.

   The old service worker deliberately cached nothing (it was a dev
   escape hatch that purged itself). This replaces it with a real
   offline shell: every app file is precached, so once the app has
   been opened one time it works with no connection at all — which
   is the whole point at a gym with bad signal.

   The precache list and the version hash are BOTH derived from the
   files, so the cache can never silently drift out of date. Change
   any file, re-run this, and every device picks the change up.

   Run:  node build-sw.mjs
   ============================================================ */
import { statSync, readFileSync, writeFileSync, rmSync, mkdirSync, copyFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// fileURLToPath, not .pathname — the folder name has spaces and parentheses
const ROOT = fileURLToPath(new URL('.', import.meta.url));
const SKIP_FILE = new Set(['sw.js', 'build-sw.mjs', 'VIDEO-TODO.md', 'MEMORY.md', 'Yates_HIT_Hybrid_Protocol.md']);
const KEEP_EXT = /\.(html|css|js|mjs|png|svg|webmanifest|json|woff2?)$/i;

/* The file list comes from GIT, not from the disk.

   This used to walk the working directory with a hardcoded skip-list, which
   meant anything sitting in the folder — an unzipped download, a scratch
   folder of artwork — was swept into the precache manifest. Those paths do
   not exist on the live site, and a precache manifest is all-or-nothing: one
   404 rejects the install event, the service worker never activates, and
   offline mode silently stops working. On an app whose whole promise is that
   a workout survives anything, that is the worst possible failure.

   Asking git removes the question. If a file is not committed, it is not on
   the live site, so it must not be in the shell. */
function listFiles() {
  const out = execFileSync('git', ['ls-files', '-z'], { cwd: ROOT, encoding: 'buffer' });
  return out.toString('utf8').split('\0')
    .filter(Boolean)
    .filter(rel => KEEP_EXT.test(rel) && !SKIP_FILE.has(rel))
    // deleted-but-still-tracked files would 404 exactly like an untracked one
    .filter(rel => { try { return statSync(join(ROOT, rel)).isFile(); } catch { return false; } });
}

const files = listFiles().sort();

/* Precache the app SHELL only. The hero images are 2–3 MB each; downloading
   ~37 MB before the app is usable would be miserable on gym wifi, and it is
   not needed — the fetch handler caches them on first view anyway, and the
   screens that matter offline (the beginner UI) do not use them at all.

   The size cap applies to MEDIA ONLY. Code is the shell: an HTML, CSS or JS
   file is precached whatever it weighs. onboarding.html quietly fell out of
   the shell when the exercise artwork went inline and pushed it past 150 KB,
   which meant the one page we are about to hand to a real user was the one
   page that did not work offline. */
const PRECACHE_MAX = 150 * 1024;
const IS_CODE = /\.(html|css|js|mjs|webmanifest|json)$/i;
const sizeOf = f => statSync(join(ROOT, f)).size;
const keep = f => IS_CODE.test(f) || sizeOf(f) <= PRECACHE_MAX;
const precache = files.filter(keep);
const deferred = files.filter(f => !keep(f));

// version = hash of every file's content, so a byte change anywhere busts the cache
const h = createHash('sha1');
for (const f of files) h.update(f).update(readFileSync(join(ROOT, f)));
const VERSION = h.digest('hex').slice(0, 10);

const sw = `/* ============================================================
   SERVICE WORKER — offline app shell.
   GENERATED by build-sw.mjs. Do not hand-edit: re-run the script.

   Strategy
     · precache the app shell on install (big images are left to
       cache on first view — see build-sw.mjs)
     · cache-first for those files — instant, and works with no signal
     · navigations fall back to the cached index.html, so opening the
       app from the home screen works offline every time
     · anything else falls back to the network
     · activating a new version deletes the old cache and tells open
       pages, which show a small "update ready" bar

   Training data lives in localStorage, not here, so an update never
   touches a logged session.
   ============================================================ */
const VERSION = '${VERSION}';
const CACHE = 'fj-' + VERSION;
const ASSETS = ${JSON.stringify(precache.map(f => './' + f.split('\\').join('/')), null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is all-or-nothing; add one at a time so a single bad path
    // can't leave the app with no offline cache at all
    await Promise.all(ASSETS.map(async (url) => {
      try { await cache.add(new Request(url, { cache: 'reload' })); }
      catch (err) { console.warn('[sw] could not precache', url, err); }
    }));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE && k.startsWith('fj-')).map(k => caches.delete(k)));
    await self.clients.claim();
    const clients = await self.clients.matchAll({ type: 'window' });
    clients.forEach(c => c.postMessage({ type: 'sw-updated', version: VERSION }));
  })());
});

self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;      // never touch third-party requests

  // a navigation (opening the app, or a refresh) must always resolve,
  // connection or not — that is what makes it feel like an installed app
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(CACHE);
        cache.put('./index.html', fresh.clone());
        return fresh;
      } catch (err) {
        const cache = await caches.open(CACHE);
        return (await cache.match('./index.html')) || Response.error();
      }
    })());
    return;
  }

  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const fresh = await fetch(req);
      if (fresh && fresh.ok && fresh.type === 'basic') cache.put(req, fresh.clone());
      return fresh;
    } catch (err) {
      return new Response('', { status: 504, statusText: 'offline' });
    }
  })());
});
`;

writeFileSync(join(ROOT, 'sw.js'), sw);
const kb = n => Math.round(n / 1024);
const shellKB = kb(precache.reduce((t, f) => t + sizeOf(f), 0));
console.log(`sw.js written — version ${VERSION}`);
console.log(`  precached: ${precache.length} files, ${shellKB} KB (the offline shell)`);
if (deferred.length) {
  // never let a coverage decision be silent
  console.log(`  NOT precached (over ${kb(PRECACHE_MAX)} KB — cached on first view instead):`);
  for (const f of deferred) console.log(`    ${String(kb(sizeOf(f))).padStart(5)} KB  ${f}`);
}

/* ---- dist/ : exactly what gets uploaded, and nothing else ----
   The project folder also holds MEMORY.md, the Yates protocol notes and
   .claude/ — none of which belong on a public URL. dist/ is built from the
   same file list the service worker precaches, so the two can't disagree. */
const DIST = join(ROOT, 'dist');
rmSync(DIST, { recursive: true, force: true });
for (const f of [...files, 'sw.js']) {
  const dest = join(DIST, f);
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(join(ROOT, f), dest);
}
console.log(`dist/ built — ${files.length + 1} files, ready to upload`);
