/* ============================================================
   SERVICE WORKER — offline app shell.
   GENERATED by build-sw.mjs. Do not hand-edit: re-run the script.

   Strategy
     · precache the app shell on install (big images are left to
       cache on first view — see build-sw.mjs)
     · cache-first for those files — instant, and works with no signal
     · navigations fall back to the cached index.html, so opening the
       app from the home screen works offline every time
     · anything else falls back to the network
     · activating a new version deletes the old cache and tells open
       pages, which show a small "update ready" bar

   Training data lives in localStorage, not here, so an update never
   touches a logged session.
   ============================================================ */
const VERSION = '6948ec9570';
const CACHE = 'fj-' + VERSION;
const ASSETS = [
  "./coach.html",
  "./dashboard.html",
  "./icon-180.png",
  "./icon-192.png",
  "./icon-512-maskable.png",
  "./icon-512.png",
  "./icon-maskable.svg",
  "./icon.svg",
  "./images/equipment/kettlebell.png",
  "./images/icon-180.png",
  "./images/icon-192.png",
  "./images/icon-512-maskable.png",
  "./images/icon-512.png",
  "./images/logo-mark.svg",
  "./images/logo-onboarding.png",
  "./images/logo.png",
  "./images/stamp-dumbbell.svg",
  "./images/stamp-triangle.svg",
  "./index.html",
  "./js/adapters/local.js",
  "./js/app.js",
  "./js/beginner.js",
  "./js/carrier.js",
  "./js/coach.js",
  "./js/composer.js",
  "./js/core/current.js",
  "./js/core/persist.js",
  "./js/core/resolve.js",
  "./js/core/schema.js",
  "./js/core/storage.js",
  "./js/data.js",
  "./js/data/exercise-images.js",
  "./js/data/exercises-gym.js",
  "./js/data/exercises.js",
  "./js/data/formats.js",
  "./js/data/program.js",
  "./js/data/sessions-beginner.js",
  "./js/data/sessions.js",
  "./js/install.js",
  "./js/intake.js",
  "./js/manifest-user.js",
  "./js/program-adapter.js",
  "./js/release.js",
  "./js/runner.js",
  "./js/runner/runstate.js",
  "./js/runner/workmode.js",
  "./js/screens/b-day.js",
  "./js/screens/b-history.js",
  "./js/screens/b-home.js",
  "./js/screens/b-summary.js",
  "./js/screens/claim.js",
  "./js/screens/day.js",
  "./js/screens/history.js",
  "./js/screens/library.js",
  "./js/screens/program.js",
  "./js/screens/week.js",
  "./js/store.js",
  "./js/timer.js",
  "./js/users.js",
  "./library.html",
  "./logo/DUMBBELL.html",
  "./logo/LOGO LAB.html",
  "./logo/LOGO PREVIEW.html",
  "./logo/WEIGHT GAUGE.html",
  "./logo/equipment.mjs",
  "./logo/hero.css",
  "./logo/hero.js",
  "./logo/mark.mjs",
  "./manifest.webmanifest",
  "./onboarding.html",
  "./profile.html",
  "./spine/aliases.json",
  "./spine/art.manifest.json",
  "./spine/benchmarks.json",
  "./spine/catalog.json",
  "./spine/program.default.json",
  "./spine/programs/beginner_return.json",
  "./spine/programs/fundamentals.json",
  "./spine/programs/index.json",
  "./spine/programs/main.json",
  "./spine/theme.json",
  "./styles.css"
];

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is all-or-nothing; add one at a time so a single bad path
    // can't leave the app with no offline cache at all
    await Promise.all(ASSETS.map(async (url) => {
      try { await cache.add(new Request(url, { cache: 'reload' })); }
      catch (err) { console.warn('[sw] could not precache', url, err); }
    }));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE && k.startsWith('fj-')).map(k => caches.delete(k)));
    await self.clients.claim();
    const clients = await self.clients.matchAll({ type: 'window' });
    clients.forEach(c => c.postMessage({ type: 'sw-updated', version: VERSION }));
  })());
});

self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;      // never touch third-party requests

  // a navigation (opening the app, or a refresh) must always resolve,
  // connection or not — that is what makes it feel like an installed app
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      // WHICH PAGE IS THIS, ACTUALLY. Every page in this app is a navigation:
      // dashboard.html, coach.html, onboarding.html. This used to write the
      // response into './index.html' whatever had been asked for, so opening
      // the console once left the console's HTML cached as the app's start
      // page - and the next offline open of the home-screen icon served it.
      // Cache each page under its own name, and only the real start page
      // under index.html.
      const path = url.pathname.split('/').pop() || 'index.html';
      const key = './' + path;
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(CACHE);
        // Only cache pages the shell actually ships; a navigation to
        // anything else is not ours to keep.
        if (ASSETS.includes(key)) cache.put(key, fresh.clone());
        return fresh;
      } catch (err) {
        const cache = await caches.open(CACHE);
        // Offline: the page asked for, then the start page. A workout must
        // open from the home screen with no signal, which is the fallback -
        // but not at the cost of serving the wrong page when we have it.
        return (await cache.match(key))
            || (await cache.match('./index.html'))
            || Response.error();
      }
    })());
    return;
  }

  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const fresh = await fetch(req);
      if (fresh && fresh.ok && fresh.type === 'basic') cache.put(req, fresh.clone());
      return fresh;
    } catch (err) {
      return new Response('', { status: 504, statusText: 'offline' });
    }
  })());
});
