/* ============================================================
   SERVICE WORKER — offline app shell.
   GENERATED by build-sw.mjs. Do not hand-edit: re-run the script.

   Strategy
     · precache the app shell on install (big images are left to
       cache on first view — see build-sw.mjs)
     · cache-first for those files — instant, and works with no signal
     · navigations fall back to the cached index.html, so opening the
       app from the home screen works offline every time
     · anything else falls back to the network
     · activating a new version deletes the old cache and tells open
       pages, which show a small "update ready" bar

   Training data lives in localStorage, not here, so an update never
   touches a logged session.
   ============================================================ */
const VERSION = '70782dae1e';
const CACHE = 'fj-' + VERSION;
const ASSETS = [
  "./ EXERCISE LIBRARY/Exercise_Illustration_Collection/03_Lower_Body_Glutes_Posterior_Chain/019_bodyweight_squat.png",
  "./ FOR NICOLAS/EXERCISE CLASSIFIER.html",
  "./.claude/launch.json",
  "./EXERCISE DATABASE/DASHBOARD.html",
  "./EXERCISE DATABASE/tools/dashboard.template.html",
  "./EXERCISE DATABASE/tools/derive.mjs",
  "./EXERCISE DATABASE/tools/fundamentals.json",
  "./EXERCISE DATABASE/tools/gym-library-seed.json",
  "./EXERCISE DATABASE/workbook/_derived.json",
  "./coach.html",
  "./dashboard.html",
  "./feed.html",
  "./hero.html",
  "./icon-180.png",
  "./icon-192.png",
  "./icon-512-maskable.png",
  "./icon-512.png",
  "./icon-maskable.svg",
  "./icon.svg",
  "./images/equipment/kettlebell.png",
  "./images/icon-180.png",
  "./images/icon-192.png",
  "./images/icon-512-maskable.png",
  "./images/icon-512.png",
  "./images/logo-onboarding.png",
  "./images/logo.png",
  "./images/stamp-dumbbell.svg",
  "./images/stamp-triangle.svg",
  "./index.html",
  "./js/adapters/local.js",
  "./js/app.js",
  "./js/beginner.js",
  "./js/coach.js",
  "./js/composer.js",
  "./js/core/persist.js",
  "./js/core/resolve.js",
  "./js/core/schema.js",
  "./js/core/storage.js",
  "./js/data.js",
  "./js/data/exercise-images.js",
  "./js/data/exercises-gym.js",
  "./js/data/exercises.js",
  "./js/data/formats.js",
  "./js/data/program.js",
  "./js/data/sessions-beginner.js",
  "./js/data/sessions.js",
  "./js/install.js",
  "./js/manifest-user.js",
  "./js/runner.js",
  "./js/runner/runstate.js",
  "./js/runner/workmode.js",
  "./js/screens/b-day.js",
  "./js/screens/b-history.js",
  "./js/screens/b-home.js",
  "./js/screens/b-summary.js",
  "./js/screens/claim.js",
  "./js/screens/day.js",
  "./js/screens/history.js",
  "./js/screens/library.js",
  "./js/screens/program.js",
  "./js/screens/week.js",
  "./js/store.js",
  "./js/timer.js",
  "./js/users.js",
  "./library.html",
  "./logo/DUMBBELL.html",
  "./logo/LOGO LAB.html",
  "./logo/LOGO PREVIEW.html",
  "./logo/WEIGHT GAUGE.html",
  "./logo/equipment.mjs",
  "./logo/hero.css",
  "./logo/hero.js",
  "./logo/mark.mjs",
  "./manifest.webmanifest",
  "./mark-compare.html",
  "./onboarding.html",
  "./preview.html",
  "./profile.html",
  "./site/coach.html",
  "./site/dashboard.html",
  "./site/icon-180.png",
  "./site/icon-192.png",
  "./site/icon-512-maskable.png",
  "./site/icon-512.png",
  "./site/icon.svg",
  "./site/images/avatars/f_a1_athletic.png",
  "./site/images/avatars/f_a1_average.png",
  "./site/images/avatars/f_a1_overweight.png",
  "./site/images/avatars/f_a1_soft.png",
  "./site/images/avatars/f_a1_thin.png",
  "./site/images/avatars/f_a2_athletic.png",
  "./site/images/avatars/f_a2_average.png",
  "./site/images/avatars/f_a2_overweight.png",
  "./site/images/avatars/f_a2_soft.png",
  "./site/images/avatars/f_a2_thin.png",
  "./site/images/avatars/f_a3_athletic.png",
  "./site/images/avatars/f_a3_average.png",
  "./site/images/avatars/f_a3_overweight.png",
  "./site/images/avatars/f_a3_soft.png",
  "./site/images/avatars/f_a3_thin.png",
  "./site/images/avatars/m_a1_athletic.png",
  "./site/images/avatars/m_a1_average.png",
  "./site/images/avatars/m_a1_overweight.png",
  "./site/images/avatars/m_a1_soft.png",
  "./site/images/avatars/m_a1_thin.png",
  "./site/images/avatars/m_a2_athletic.png",
  "./site/images/avatars/m_a2_average.png",
  "./site/images/avatars/m_a2_overweight.png",
  "./site/images/avatars/m_a2_soft.png",
  "./site/images/avatars/m_a2_thin.png",
  "./site/images/avatars/m_a3_athletic.png",
  "./site/images/avatars/m_a3_average.png",
  "./site/images/avatars/m_a3_overweight.png",
  "./site/images/avatars/m_a3_soft.png",
  "./site/images/avatars/m_a3_thin.png",
  "./site/images/exercises/active_hang.png",
  "./site/images/exercises/back_extension_45.png",
  "./site/images/exercises/back_squat.png",
  "./site/images/exercises/banded_glute_bridge.png",
  "./site/images/exercises/banded_pullapart.png",
  "./site/images/exercises/banded_sidewalk.png",
  "./site/images/exercises/bench_press.png",
  "./site/images/exercises/bent_over_row.png",
  "./site/images/exercises/bird_dog.png",
  "./site/images/exercises/bird_dog_crunch.png",
  "./site/images/exercises/bodyweight_squat.png",
  "./site/images/exercises/bulgarian_split.png",
  "./site/images/exercises/cat_cow.png",
  "./site/images/exercises/chest_to_bar.png",
  "./site/images/exercises/chin_up.png",
  "./site/images/exercises/db_swing.png",
  "./site/images/exercises/dead_bug.png",
  "./site/images/exercises/dead_hang.png",
  "./site/images/exercises/deadlift.png",
  "./site/images/exercises/deadstop_pushup.png",
  "./site/images/exercises/deep_pike_pushup.png",
  "./site/images/exercises/deep_squat_rock.png",
  "./site/images/exercises/dip.png",
  "./site/images/exercises/dip_support_hold.png",
  "./site/images/exercises/down_dog_up_dog.png",
  "./site/images/exercises/dragon_flag.png",
  "./site/images/exercises/explosive_chinup.png",
  "./site/images/exercises/farmers_carry.png",
  "./site/images/exercises/forearm_plank.png",
  "./site/images/exercises/full_burpee.png",
  "./site/images/exercises/handstand.png",
  "./site/images/exercises/hanging_knee_raise.png",
  "./site/images/exercises/hip_cars.png",
  "./site/images/exercises/hip_thrust.png",
  "./site/images/exercises/hollow_hold.png",
  "./site/images/exercises/hollow_rocks.png",
  "./site/images/exercises/horse_stance.png",
  "./site/images/exercises/jump_squat.png",
  "./site/images/exercises/kb_swing.png",
  "./site/images/exercises/l_sit_pullup.png",
  "./site/images/exercises/man_maker.png",
  "./site/images/exercises/mountain_climber.png",
  "./site/images/exercises/muscle_up_bar.png",
  "./site/images/exercises/navy_seal_burpee.png",
  "./site/images/exercises/overhead_press.png",
  "./site/images/exercises/pike_push_up.png",
  "./site/images/exercises/pseudo_planche_push_up.png",
  "./site/images/exercises/pullup.png",
  "./site/images/exercises/pushup.png",
  "./site/images/exercises/ring_dip.png",
  "./site/images/exercises/ring_dip_support_hold.png",
  "./site/images/exercises/single_leg_rdl.png",
  "./site/images/exercises/straight_bar_dip.png",
  "./site/images/exercises/straight_bar_push_up.png",
  "./site/images/exercises/turkish_getup.png",
  "./site/images/exercises/wall_sit.png",
  "./site/images/exercises/wide_inverted_row.png",
  "./site/images/icon-180.png",
  "./site/images/icon-192.png",
  "./site/images/icon-512-maskable.png",
  "./site/images/icon-512.png",
  "./site/images/logo-onboarding.png",
  "./site/images/logo.png",
  "./site/images/stamp-dumbbell.svg",
  "./site/images/stamp-triangle.svg",
  "./site/index.html",
  "./site/manifest.webmanifest",
  "./site/onboarding.html",
  "./site/spine/aliases.json",
  "./site/spine/art.manifest.json",
  "./site/spine/benchmarks.json",
  "./site/spine/catalog.json",
  "./site/spine/theme.json",
  "./spine/aliases.json",
  "./spine/art.manifest.json",
  "./spine/benchmarks.json",
  "./spine/catalog.json",
  "./spine/theme.json",
  "./styles.css",
  "./tools/audit-classes.mjs",
  "./tools/audit-survey-wiring.mjs",
  "./tools/build-app-data.mjs",
  "./tools/build-avatars.mjs",
  "./tools/build-benchmarks.mjs",
  "./tools/build-classifier.mjs",
  "./tools/build-deck-art.mjs",
  "./tools/build-equipment.mjs",
  "./tools/build-exercise-images.mjs",
  "./tools/build-logo.mjs",
  "./tools/build-spine.mjs",
  "./tools/fix-progression-links.mjs"
];

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is all-or-nothing; add one at a time so a single bad path
    // can't leave the app with no offline cache at all
    await Promise.all(ASSETS.map(async (url) => {
      try { await cache.add(new Request(url, { cache: 'reload' })); }
      catch (err) { console.warn('[sw] could not precache', url, err); }
    }));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE && k.startsWith('fj-')).map(k => caches.delete(k)));
    await self.clients.claim();
    const clients = await self.clients.matchAll({ type: 'window' });
    clients.forEach(c => c.postMessage({ type: 'sw-updated', version: VERSION }));
  })());
});

self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;      // never touch third-party requests

  // a navigation (opening the app, or a refresh) must always resolve,
  // connection or not — that is what makes it feel like an installed app
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(CACHE);
        cache.put('./index.html', fresh.clone());
        return fresh;
      } catch (err) {
        const cache = await caches.open(CACHE);
        return (await cache.match('./index.html')) || Response.error();
      }
    })());
    return;
  }

  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const fresh = await fetch(req);
      if (fresh && fresh.ok && fresh.type === 'basic') cache.put(req, fresh.clone());
      return fresh;
    } catch (err) {
      return new Response('', { status: 504, statusText: 'offline' });
    }
  })());
});
