/* ============================================================
   SERVICE WORKER — offline app shell.
   GENERATED by build-sw.mjs. Do not hand-edit: re-run the script.

   Strategy
     · precache the app shell on install (big images are left to
       cache on first view — see build-sw.mjs)
     · cache-first for those files — instant, and works with no signal
     · navigations fall back to the cached index.html, so opening the
       app from the home screen works offline every time
     · anything else falls back to the network
     · activating a new version deletes the old cache and tells open
       pages, which show a small "update ready" bar

   Training data lives in localStorage, not here, so an update never
   touches a logged session.
   ============================================================ */
const VERSION = '47588e6038';
const CACHE = 'fj-' + VERSION;
const ASSETS = [
  "./icon.svg",
  "./images/icon-180.png",
  "./images/icon-192.png",
  "./images/icon-512-maskable.png",
  "./images/icon-512.png",
  "./images/logo.png",
  "./index.html",
  "./js/app.js",
  "./js/beginner.js",
  "./js/coach.js",
  "./js/composer.js",
  "./js/core/resolve.js",
  "./js/data.js",
  "./js/data/exercises-gym.js",
  "./js/data/exercises.js",
  "./js/data/formats.js",
  "./js/data/program.js",
  "./js/data/sessions-beginner.js",
  "./js/data/sessions.js",
  "./js/runner.js",
  "./js/runner/runstate.js",
  "./js/runner/workmode.js",
  "./js/screens/b-day.js",
  "./js/screens/b-home.js",
  "./js/screens/b-summary.js",
  "./js/screens/day.js",
  "./js/screens/history.js",
  "./js/screens/library.js",
  "./js/screens/program.js",
  "./js/screens/week.js",
  "./js/store.js",
  "./js/timer.js",
  "./js/users.js",
  "./library.html",
  "./manifest.webmanifest",
  "./onboarding.html",
  "./styles.css",
  "./verify3.js"
];

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is all-or-nothing; add one at a time so a single bad path
    // can't leave the app with no offline cache at all
    await Promise.all(ASSETS.map(async (url) => {
      try { await cache.add(new Request(url, { cache: 'reload' })); }
      catch (err) { console.warn('[sw] could not precache', url, err); }
    }));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE && k.startsWith('fj-')).map(k => caches.delete(k)));
    await self.clients.claim();
    const clients = await self.clients.matchAll({ type: 'window' });
    clients.forEach(c => c.postMessage({ type: 'sw-updated', version: VERSION }));
  })());
});

self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;      // never touch third-party requests

  // a navigation (opening the app, or a refresh) must always resolve,
  // connection or not — that is what makes it feel like an installed app
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const cache = await caches.open(CACHE);
        cache.put('./index.html', fresh.clone());
        return fresh;
      } catch (err) {
        const cache = await caches.open(CACHE);
        return (await cache.match('./index.html')) || Response.error();
      }
    })());
    return;
  }

  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const fresh = await fetch(req);
      if (fresh && fresh.ok && fresh.type === 'basic') cache.put(req, fresh.clone());
      return fresh;
    } catch (err) {
      return new Response('', { status: 504, statusText: 'offline' });
    }
  })());
});
