#!/usr/bin/env node
/* ============================================================
   THE LAB. A second dashboard, for Nicolas only.

   Run:  node tools/build-lab.mjs

   WHAT IT IS. dashboard-lab.html is dashboard.html with two extra
   files layered on top: lab/lab.css and lab/lab.js. Same data, same
   code, same training. A different look, and only where lab/ says so.

   WHY IT IS GENERATED AND NOT A COPY. A copy of a 7000 line file is a
   fork, and a fork rots: every fix to the real dashboard would have to
   be made twice, and within a fortnight the lab would be a museum of
   last month. This is rebuilt from the real one every time, so the lab
   is ALWAYS the current dashboard plus the experiments, and never an
   old dashboard pretending.

   HOW AN EXPERIMENT WORKS. Put it in lab/lab.css or lab/lab.js. It
   only exists in the lab. Nothing a client can open changes.

   HOW IT GRADUATES. When Nicolas likes something, it moves into
   dashboard.html properly and comes OUT of lab/. The lab is a place to
   try things, never a place things live. An experiment that has been
   in there a month is a decision nobody has made.

   IT IS NOT SECRET, IT IS UNLISTED. Anybody who types the URL can open
   it. Nothing links to it, no client is ever sent there, and it is
   kept out of the offline shell so it is not downloaded onto phones
   that will never open it. That is the right amount of hiding for a
   thing whose worst case is a coach seeing an odd layout.
   ============================================================ */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'dashboard.html');
const OUT = join(ROOT, 'dashboard-lab.html');

let html = readFileSync(SRC, 'utf8');

if (!existsSync(join(ROOT, 'lab', 'lab.css')) || !existsSync(join(ROOT, 'lab', 'lab.js'))) {
  console.error('  lab/lab.css and lab/lab.js must both exist. Nothing written.');
  process.exit(1);
}

/* A BANNER, BECAUSE MISTAKING THE TWO IS THE ONLY REAL RISK HERE.
   Judging a layout you think is live, or reporting a bug in the lab as
   a bug in the app, both waste an afternoon. It says which one this is
   and links back to the real one. */
const BANNER = `
<div id="labflag">
  <b>LAB</b>
  <span>Experiments. Your real training, a layout nobody else can see.</span>
  <a href="dashboard.html">Open the real one</a>
</div>`;

const HEAD = `  <link rel="stylesheet" href="lab/lab.css">\n`;
const TAIL = `${BANNER}\n<script src="lab/lab.js"></script>\n`;

/* Generated files say so, in the file, where somebody who opens it by
   accident will see it before they edit the wrong thing. */
const STAMP = `<!-- ============================================================
     GENERATED by tools/build-lab.mjs from dashboard.html. DO NOT EDIT.

     Every edit here is lost on the next build. The experiments live in
     lab/lab.css and lab/lab.js; the rest is dashboard.html, verbatim.
     ============================================================ -->\n`;

html = html.replace(/<title>[^<]*<\/title>/, '<title>Fitness Journey - LAB</title>');
html = html.replace('</head>', HEAD + '</head>');
html = html.replace('</body>', TAIL + '</body>');
html = STAMP + html;

writeFileSync(OUT, html);

const bytes = Buffer.byteLength(html);
console.log(`  dashboard-lab.html written, ${(bytes / 1024).toFixed(0)} KB.`);
console.log('  Open it at /dashboard-lab.html. Experiments go in lab/lab.css and lab/lab.js.');
console.log('  Rebuild after any change to dashboard.html, or the lab is showing you last week.');
