/* ============================================================
   WHAT TO DRAW NEXT, IN THE ORDER THAT MATTERS.

   Run:  node tools/images-to-make.mjs

   249 of 307 movements have no picture. A flat list of 249 is not a
   work queue - it is a wall. So this ranks them by how close each one
   sits to a movement that actually matters:

     1  a FUNDAMENTAL with no picture
     2  one step from a fundamental - its easier or its harder version,
        which is what a person is offered the moment a fundamental is
        too hard or too easy
     3  two steps out along the same ladder
     4  used by a real program, but not near a fundamental
     5  everything else

   The ladder is the `easier` / `harder` fields in the database, which
   186 and 118 movements already carry. Adjacency is walked in both
   directions: a movement that names a fundamental as its harder version
   is just as adjacent as one the fundamental names itself.

   Writes " FOR NICOLAS/IMAGES TO MAKE.md" - a plain checklist, one
   movement per line, made to be copied out.
   ============================================================ */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, nicolas, must } from './paths.mjs';

const cat = JSON.parse(readFileSync(join(ROOT, 'spine/catalog.json'), 'utf8')).movements;
const all = Object.values(cat);
const has = m => m.art && m.art.status === 'drawn';

/* which movements a real program asks for */
const used = new Set();
const pdir = join(ROOT, 'spine/programs');
for (const f of readdirSync(pdir)) {
  if (!f.endsWith('.json') || f === 'index.json') continue;
  const p = JSON.parse(readFileSync(join(pdir, f), 'utf8'));
  for (const d of Object.values(p.days || {}))
    for (const b of d.blocks || []) for (const it of b.items || []) used.add(it.ex);
}

/* the ladder, both ways */
const near = new Map();                       // id -> steps from a fundamental
const link = id => {
  const m = cat[id]; if (!m) return [];
  const out = [m.easier, m.harder].filter(Boolean);
  for (const o of all) if (o.easier === id || o.harder === id) out.push(o.id);
  return out;
};
let frontier = all.filter(m => m.fundamental).map(m => m.id);
frontier.forEach(id => near.set(id, 0));
for (let step = 1; step <= 2 && frontier.length; step++) {
  const next = [];
  for (const id of frontier) for (const n of link(id))
    if (!near.has(n)) { near.set(n, step); next.push(n); }
  frontier = next;
}

/* THE LADDER HAS A FEW BROKEN RUNGS, and a queue built on it should
   say so rather than quietly walking off the end. Two movements name
   themselves as their own harder version, and four point at ids that do
   not exist. None of it breaks this list - it just makes those rungs
   dead - but nobody would ever notice from the outside. */
const brokenLadder = [];
for (const m of all) {
  for (const k of ['easier','harder']) {
    const v = m[k]; if (!v) continue;
    if (v === m.id) brokenLadder.push(`${m.name} — ${k} points at itself`);
    else if (!cat[v]) brokenLadder.push(`${m.name} — ${k} "${v}" is not a movement`);
  }
}

const TIER = m =>
  m.fundamental        ? 1 :
  near.get(m.id) === 1 ? 2 :
  near.get(m.id) === 2 ? 3 :
  used.has(m.id)       ? 4 : 5;
const LABEL = { 1:'FUNDAMENTALS', 2:'ONE STEP FROM A FUNDAMENTAL',
                3:'TWO STEPS FROM A FUNDAMENTAL', 4:'USED BY A PROGRAM', 5:'EVERYTHING ELSE' };

const todo = all.filter(m => !has(m)).map(m => ({ m, t: TIER(m) }))
  .sort((a,b) => a.t - b.t || a.m.name.localeCompare(b.m.name));

let out = `# Exercise images — what to draw, in order\n\n`;
out += `Generated by \`node tools/images-to-make.mjs\` on ${new Date().toISOString().slice(0,10)}.\n\n`;
out += `**${all.filter(has).length} of ${all.length} movements have a picture. ${todo.length} do not.**\n\n`;
out += `Ranked by how close each one sits to a movement that matters — a fundamental first,\n`;
out += `then the versions a person is offered when a fundamental is too hard or too easy.\n`;
out += `Numbered straight through, one movement per line. Draw it, save it as \`<id>.png\`,\n`;
out += `drop it in the artwork folder. The number is only so you can say where you got to.\n`;
if (brokenLadder.length) {
  out += `\n> **${brokenLadder.length} broken rungs in the easier/harder ladder**, found while ranking this list.\n`;
  out += `> They do not affect the order, they just make those rungs dead ends in the app.\n`;
  brokenLadder.forEach(x => { out += `> - ${x}\n`; });
}

/* ONE LINE PER MOVEMENT, NUMBERED STRAIGHT THROUGH.

   This is a list somebody works down, drawing as they go - so a number
   that does not restart at each heading is the difference between "I am
   on 63" and counting sections. The detail that used to sit on a second
   indented line is on the same line now: a two-line entry reads as two
   jobs. */
let last = null, n = 0;
for (const { m, t } of todo) {
  if (t !== last) {
    const count = todo.filter(x => x.t === t).length;
    out += `\n\n## ${t}. ${LABEL[t]}  ·  ${count}\n\n`;
    last = t;
  }
  n++;
  const bits = [m.pattern, (m.equipment || []).join('/')].filter(Boolean).join(' · ');
  out += `${String(n).padStart(3)}. \`${m.id}\` — ${m.name}${m.fundamental ? ' ★' : ''}  ·  ${bits}\n`;
}

const dest = join(must(nicolas(), 'FOR NICOLAS'), 'IMAGES TO MAKE.md');
writeFileSync(dest, out);
const byTier = {};
todo.forEach(x => byTier[x.t] = (byTier[x.t]||0)+1);
console.log(`${todo.length} movements need a picture\n`);
for (const t of [1,2,3,4,5]) if (byTier[t]) console.log(`  ${t}. ${LABEL[t].padEnd(30)} ${byTier[t]}`);
console.log(`\nwritten to FOR NICOLAS/IMAGES TO MAKE.md`);
if (brokenLadder.length) {
  console.log(`\n  ${brokenLadder.length} broken rung(s) in the easier/harder ladder — fix in the workbook:`);
  brokenLadder.forEach(x => console.log('     ' + x));
}
